server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Taro2021/springcloud-config.git
          search-paths:
            - springcloud-config
        default-label: main
  rabbitmq:
    host: 121.199.78.94
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka